<a href="https://colab.research.google.com/github/aritro66/Parkinson-s-Disease-Detection/blob/main/Parkinson'sDiseaseDetection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the Dependencies

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn import svm;

Collecting and Processing Data

In [3]:
# Loading the dataset using Pandas function
disease_data = pd.read_csv('/content/parkinsons.csv')

In [4]:
# Checking data of first 5 rows
disease_data.head()

             name  MDVP:Fo(Hz)  MDVP:Fhi(Hz)  ...   spread2        D2       PPE
0  phon_R01_S01_1      119.992       157.302  ...  0.266482  2.301442  0.284654
1  phon_R01_S01_2      122.400       148.650  ...  0.335590  2.486855  0.368674
2  phon_R01_S01_3      116.682       131.111  ...  0.311173  2.342259  0.332634
3  phon_R01_S01_4      116.676       137.871  ...  0.334147  2.405554  0.368975
4  phon_R01_S01_5      116.014       141.781  ...  0.234513  2.332180  0.410335

[5 rows x 24 columns]

In [5]:
# Checking data of last 5 rows
disease_data.tail()

               name  MDVP:Fo(Hz)  MDVP:Fhi(Hz)  ...   spread2        D2       PPE
190  phon_R01_S50_2      174.188       230.978  ...  0.121952  2.657476  0.133050
191  phon_R01_S50_3      209.516       253.017  ...  0.129303  2.784312  0.168895
192  phon_R01_S50_4      174.688       240.005  ...  0.158453  2.679772  0.131728
193  phon_R01_S50_5      198.764       396.961  ...  0.207454  2.138608  0.123306
194  phon_R01_S50_6      214.289       260.277  ...  0.190667  2.555477  0.148569

[5 rows x 24 columns]

In [6]:
# No. of rows and columns
disease_data.shape

(195, 24)

In [10]:
# Statistical info
disease_data.describe()

       MDVP:Fo(Hz)  MDVP:Fhi(Hz)  ...          D2         PPE
count   195.000000    195.000000  ...  195.000000  195.000000
mean    154.228641    197.104918  ...    2.381826    0.206552
std      41.390065     91.491548  ...    0.382799    0.090119
min      88.333000    102.145000  ...    1.423287    0.044539
25%     117.572000    134.862500  ...    2.099125    0.137451
50%     148.790000    175.829000  ...    2.361532    0.194052
75%     182.769000    224.205500  ...    2.636456    0.252980
max     260.105000    592.030000  ...    3.671155    0.527367

[8 rows x 23 columns]

In [11]:
# Getting basic information about data
disease_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              195 non-null    object
 1   MDVP:Fo(Hz)       195 non-null    float64
 2   MDVP:Fhi(Hz)      195 non-null    float64
 3   MDVP:Flo(Hz)      195 non-null    float64
 4   MDVP:Jitter(%)    195 non-null    float64
 5   MDVP:Jitter(Abs)  195 non-null    float64
 6   MDVP:RAP          195 non-null    float64
 7   MDVP:PPQ          195 non-null    float64
 8   Jitter:DDP        195 non-null    float64
 9   MDVP:Shimmer      195 non-null    float64
 10  MDVP:Shimmer(dB)  195 non-null    float64
 11  Shimmer:APQ3      195 non-null    float64
 12  Shimmer:APQ5      195 non-null    float64
 13  MDVP:APQ          195 non-null    float64
 14  Shimmer:DDA       195 non-null    float64
 15  NHR               195 non-null    float64
 16  HNR               195 non-null    float64
 17  status            195 non-null    int64
 18  RPDE              195 non-null    float64
 19  DFA               195 non-null    float64
 20  spread1           195 non-null    float64
 21  spread2           195 non-null    float64
 22  D2                195 non-null    float64
 23  PPE               195 non-null    float64
dtypes: float64(22), int64(1), object(1)
memory usage: 36.7+ KB

In [12]:
# Finding missing values
disease_data.isnull().sum()

name                0
MDVP:Fo(Hz)         0
MDVP:Fhi(Hz)        0
MDVP:Flo(Hz)        0
MDVP:Jitter(%)      0
MDVP:Jitter(Abs)    0
MDVP:RAP            0
MDVP:PPQ            0
Jitter:DDP          0
MDVP:Shimmer        0
MDVP:Shimmer(dB)    0
Shimmer:APQ3        0
Shimmer:APQ5        0
MDVP:APQ            0
Shimmer:DDA         0
NHR                 0
HNR                 0
status              0
RPDE                0
DFA                 0
spread1             0
spread2             0
D2                  0
PPE                 0
dtype: int64

In [15]:
# number of values for status
disease_data["status"].value_counts()

1    147
0     48
Name: status, dtype: int64

1 represents suffering from Parkinson's disease

0 represents not suffering from Parkinson's disease

In [16]:
# grouping the data based on the target variable
disease_data.groupby('status').mean()

        MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  ...   spread2        D2       PPE
status                                           ...
0        181.937771    223.636750    145.207292  ...  0.160292  2.154491  0.123017
1        145.180762    188.441463    106.893558  ...  0.248133  2.456058  0.233828

[2 rows x 22 columns]

In [18]:
# Separating data and labels
X = disease_data.drop(columns=['status','name'],axis=1)
Y = disease_data['status']
print(X.shape)
print(Y.shape)

(195, 22)
(195,)

Training and Testing data

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=2)

Data Standardization

In [29]:
scalar = StandardScaler()

In [30]:
scalar.fit(X_train)

StandardScaler()

In [31]:
# Transforming Data
X_train = scalar.transform(X_train)
X_test = scalar.transform(X_test)

Modal Training using SVM

In [32]:
classifier = svm.SVC(kernel='linear')
classifier.fit(X_train,y_train)

SVC(kernel='linear')

Modal Evalution

In [33]:
# Accuracy of Training Data
train_prediction = classifier.predict(X_train)
print('Accuracy of Training Data : ',accuracy_score(y_train,train_prediction))

Accuracy of Training Data :  0.8846153846153846

In [34]:
# Accuracy of Testing Data
test_prediction = classifier.predict(X_test)
print('Accuracy of Testing Data : ',accuracy_score(y_test, test_prediction))

Accuracy of Testing Data :  0.8717948717948718

Making a Prediction using certain input

In [36]:
input_data=np.array([119.99200,157.30200,74.99700,0.00784,0.00007,0.00370,0.00554,0.01109,0.04374,0.42600,0.02182,0.03130,0.02971,0.06545,0.02211,21.03300,0.414783,0.815285,-4.813031,0.266482,2.301442,0.284654])

# Reshaping Array
input_data=input_data.reshape(1,-1)
# Standardize Array
input_data=scalar.transform(input_data)
prediction = classifier.predict(input_data)

if(prediction[0]==0):
  print("Not suffering from Parkinson's disease.")
else:
  print("suffering from Parkinson's disease.")

suffering from Parkinson's disease.

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"

Correct Prediction